# флаг --read-only при запуске, чтобы файловая система была только для чтения
# флаг --cap-drop=ALL, чтобы сбросить все привилегии ядра линукс
# флаг --no-new-privileges запретит процессам повышать свои права

FROM langchain/langchain:0.1.0

RUN useradd -m megaroot
USER megaroot