FROM alpine:latest

# создаем пользвателя и переключаемся на него
RUN adduser -D -u 1000 simpleuser
USER simpleuser

# создаем папку для пользователя
WORKDIR /home/appuser

CMD ["sh"]

# доп варианты безопасности
# 1. USER simpleuser — запуск не от root
# 2. --cap-drop=ALL при запуске — убирает все привилегии
# 3. --read-only при запуске — запрещает запись в файловую систему
# 4. --security-opt=no-new-privileges — запрещает повышение прав
# 5. --memory=256m — ограничение памяти
# 6. --cpus=0.5 — ограничение CPU
# 7. --pids-limit=100 — ограничение числа процессов
# 8. --user=1000:1000 — явный запуск от UID пользователя
# 9. --restart=on-failure:5 — ограничение перезапусков



